### ISSUE TITLE
How to hide TALMemo's scrollbar?

### ISSUE THREAD

**Issue by bagualing** [Zeus64/alcinoe#114]
Hi,
As mentioned in the title, my Firemonkey program runs on Windows, and I need to hide the scrollbar of TALMemo. But I didn't find how to achieve it.

**Comment by Zeus64** [comment]
TALMemo, TALEdit, etc. are not very well designed to work on windows. they are mostly made to work on android/ios. on windows TALMemo is just a wrapper of TMemo. But you are right I see that we miss the ShowScrollBar property :( mostly because on ios / android the scrollbar is always hidden and showed only when you move your finger on the screen so I never had the need to hide the scrollbar. as the Tmemo have this property it's will be not difficult to make a wrapper to this property from TALScrollBar
