### ISSUE TITLE
Memo Issues with certain Samsung phone

### ISSUE THREAD

**Issue by CFLDevelopers** [Zeus64/alcinoe#12]
[log.txt](https://github.com/Zeus64/alcinoe/files/2096223/log.txt)

I am using the almemo component for android as the Delphi supplied one has problem on samsung phones. The AlMomo works fine but the app dies if i try to double click or long press. Is it something that you have a look. I have attached the log cat file.

Thanks

**Comment by Zeus64** [comment]
Hmm, i test on many samsumg phone, what version of the android api is on the phone ?

the error: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/alcinoe/R$dimen;
mean you maybe forget to include in the deployment of your project all the files located in C:\Dev\Alcinoe\lib\jar\com.alcinoe\res

these file are mostly used in Android api <= lollipop (because on  api <= lollipop the copy/past is not a popup but an ugly top bar on the app that we can't easily emulate on delphi app)

i know it's painfull but it's how android work :(

see the little explanation i made under Alcinoe\demos\ALFmxControls\_source\android\AddRJavaToClassesDex.bat and use DeployMan.bat to include automatiquelly all the file

**Comment by Zeus64** [comment]
Ok, this is the problem ! you must also deploy all the resource files ... see the alfmxControls demo for example. You can use DeployMan.bat to not have to add manually each file one by by in the deployment.

**Comment by CFLDevelopers** [comment]
Thanks it did work with the changes that you suggested.
