### ISSUE TITLE
Downloading alcinoe lib

### ISSUE THREAD

**Issue by soinalastudio** [Zeus64/alcinoe#141]
Can you provide a proper way to download this very good lib? Downloading it is painful for slower connection. It's better to remove from the repository all compiled samples win32 & win64. Or make an release with only source files. 
I'm downloading the lib now and 570Mb downloaded, it's not finished yet... :(
Thank you

**Comment by Zeus64** [comment]
Hi, I m really sorry about this, I understand the pain :( the problem is that the compiled sample is very usefull to let user try the lib and see it in action without installing it and compiling everything (that can be sometime a little hard to do). You run the exe or install the apk in your android phone and see/understand immediatly the benefice of the lib and you can then decide to spend time to install it
