### ISSUE TITLE
I have a question over TALEdit repaint 

### ISSUE THREAD

**Issue by marcosnielsen** [Zeus64/alcinoe#23]
Hello!

I downloaded your codes and I really enjoyed the work!

My biggest problem with Firemonkey are the TEdit natives that have many bugs running on Android.
So I'm looking for a compiler to replace the Delphi TEdit.
I found in your repository just what I need: a better Edit

But I do not know what I'm doing wrong:

When placing inside a TALVertScrooBox 3 or more TALEdit Running the app in ANDRID the application loses its fluidity, and I see the components being painted in slow motion.

I used the DoubleBuffered = true property.
But that did not solve.

What am I doing wrong?

**Comment by Zeus64** [comment]
> When placing inside a TALVertScrooBox 3 or more TALEdit Running the app in ANDRID the application loses its fluidity, and I see the components being painted in slow motion.

Yes that the biggest problem with native android control (with android in fact) : The window animation is a disaster :( To resume TalEdit is a native android TextEdit put in a window on the top of the form (imagine that a form is just like a paint). that work great, but as soon as you need to scroll (ie: move the windows of the tALEdit) it's slow, and if you have more than one TEdit it's can be totally horrible.

I don't think their is any way out possible about this, it's how android work with animation of window. The only way out is to make your design so that user don't need to scroll the Edit (use for exemple TALTABControl)

**please don't forget to star (like) this project of ghitub if you like it**
