### ISSUE TITLE
TALText + HTML

### ISSUE THREAD

**Issue by kazuser** [Zeus64/alcinoe#31]
![altext](https://user-images.githubusercontent.com/3335273/45375975-6da80b80-b618-11e8-8472-8f97b0e0fcba.gif)

Why "bbb" is bold?
Where is the line break?

**Comment by Zeus64** [comment]
TalText support right now only very simple html tag, like <b>...</b>, <i>...</i>, <font color="#ffffff">...</font> and <span id="xxx">...</span>

<br> is not supported and it is here translated to <b> (bold) (and that is a bug), You can use instead of <br> :  #13#10

It's must be very easy to update the source code to support <br> by the way (simple replace all <br> by #13#10 before the process,, but didn't yet have time to add it

**Comment by Zeus64** [comment]
please don't forget to "star" (like) this project in Ghitub! It's cost nothing but help to reference the code

**Comment by emrahkucukali** [comment]
i try to do badge with altext. AutoSize= Width; and text horz center. I want to add space to text but end of string spaces nonesence. Actually i wan to add space begin and end  of string. How to do?

**Comment by Zeus64** [comment]
try to add `&nbsp;`
