### ISSUE TITLE
Commercial Version

### ISSUE THREAD

**Issue by azzahrah** [Zeus64/alcinoe#59]
This good component but less  support, so i ask is there a commercial version for more support?

**Comment by Zeus64** [comment]
I fully agree that it's quite complicated to understand how to make the library working, especially libraries like WebRTC (liveVideoChat) who even require to patch the SDK directory to use D8.bat instead of DX.bat. I would like to join TMSSoftware (I already start discussing it with @BrunoFierens) but actually, I terribly miss time to handle it right now :( I just put everything public to help the community, even if it's not good, better than nothing ...

**Comment by azzahrah** [comment]
I Hope ready for commercial version as soon as possible
