### ISSUE TITLE
compiled  with a different  version of FMX.types3D.Tmaterial

### ISSUE THREAD

**Issue by tianshangyuan** [Zeus64/alcinoe#66]
[dcc32 Fatal Error] FMX.Types.pas(1023):F2051 unit FMX.Materials was compiled with a different version of FMX.Types3D.Material

rio 10.3.1
what should i do to solve this problem?

**Comment by Spelt** [comment]
you need to include FMX.Materials from Delphi. There will be more compile errors like this.  This is because there a some changes in the original sources.  You must inlude them all or you can add the original source paths after the Alcinoe paths in the lib search.

**Comment by tianshangyuan** [comment]
thanks

**Comment by tianshangyuan** [comment]
it  works,and thank you

**Comment by RODRIGOCOLLARES** [comment]
> you need to include FMX.Materials from Delphi. There will be more compile errors like this. This is because there a some changes in the original sources. You must include them all OR you can add the original source paths after the Alcinoe paths in the lib search.

Hi, I did exactly what you said, but I still have the same problem: "Such a unit was compiled by a different version". I'm having a blank test form and I've just added a TALLAYOUT and a Component from the TEECHART lecture.

**Comment by checkdigits** [comment]
@RODRIGOCOLLARES Your paths must still be wrong.  If you are using Delphi 10 you need to ensure that the include paths are in the right order so that the Alcinoe units are found first in the search/include paths.

This can be a little in D10 - you need to make sure the *defaults* are correct because many of them are inherited for other targets such as Android.  Since you say it happens in what appears to be a nearly blank App then it's likely to be the paths in "All configurations - All Platforms"-->Delphi Compiler-->Search Path

You really only need the Android target to be modified but it does sound like you also need to look at the above options too.

See this screen shot for what I am referring to - the Alcinoe units _must_ come before everything else for it to work.

![image](https://user-images.githubusercontent.com/2126394/62141201-cb395b00-b2b1-11e9-947f-b18d7ff2ea62.png)

**Comment by RODRIGOCOLLARES** [comment]
Thank you very much
