### ISSUE TITLE
 Incompatibility with other components

### ISSUE THREAD

**Issue by RODRIGOCOLLARES** [Zeus64/alcinoe#70]
First of all congratulations for the excellent work. 
I use to say that when a component is really good, we become dependent on it, and I believe the Alcinoe is even among these. Let's get into the problem. I installed the Component in Delphi 10.3.2. I did everything you ordered, including in the library path the delphi \source\fmx install folder, as well as the resources .... \ patched \ component folder ... The Component works perfectly, even in combination with the natives, but when I try to use other installed components, such as RapidDesign, TeeChart and others, there are always compilation errors for units. The delphi informs me that a unit X, Y or Z was compiled by another version, and then I can not execute the code (I have already tried everything, including adding the paths I mentioned above in the project search path as well), but nothing solves it. The detail is that the RapidDesign component (this is just an example) worked before installing Alcinoe and the others too, now it no longer works. Everything works out when I shoot the Alcinoe ... But I can not be without it ...
Please, could you help me .... Thank you very much, big hug.

**Comment by Zeus64** [comment]
Hi, thank :)
"unit X, Y or Z was compiled by another version" it's because I was forced to patch the delphi source code (you can found the patched unit in \Alcinoe\references\embarcadero\rio\10_3_1\patched)

so when you have this error you just need to copy in your path the unit X, Y or Z that you can found in C:\Program Files (x86)\Embarcadero\Studio\20.0\source) or in your external library source code

Note: right now i didn't yet do the patch for 10.3.2 but i guess the modifications between 10.3.1 and 10.3.2 are very minor

**Comment by RODRIGOCOLLARES** [comment]
thank you very much
