### ISSUE TITLE
Windows painting performance

### ISSUE THREAD

**Issue by Spelt** [Zeus64/alcinoe#83]
Hi,

Thanks for this great component set!  I'm using the FMX Gui stuff mostly for scrolling lots of (big) images and animations in the listview.  

On IOS and Android the performance is superb and does not disappoint.  I do have a performance issue with Windows (which I did not expect). I just can't get scrolling smooth maybe you or someone else can help out.

I have a test project included.  It does not matter if the Interval in AniCalculations is higher or FMX.Types.GlobalUseGPUCanvas := true.  

Is it the writing of the bitmaps in Windows which are too slow?  I noticed that just dragging images is fine when panning (left mouse down with scroll up/down). It is when AniCalculations kicks in by mouse up.

I know the lib is optimized for mobile but maybe you know what the problem is? The bitmaps are double buffered TALImages

Hope you can help.

[test alcinoe windows scroll.zip](https://github.com/Zeus64/alcinoe/files/3828636/test.alcinoe.windows.scroll.zip)

**Comment by Zeus64** [comment]
Unfortunately on windows yes it's slower :( I didn't implement direct api call in windows like I did on iOS/android and use instead the Tbitmap/Tcanvas implementation that is not super optimized (not multithread also). Also windows use directX (even with GlobalUseGPUCanvas) where on iOS/android it's use OpenGL (not sure if this is the root cause of the problem)
